branches:
  - name: main
    prerelease: false
  - alpha
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/changelog"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/git"